Bug #107 G$ Rewards - Value in USD does not correspond to G$ price.
GoodDollar/GoodProtocolUI pull request #125
Opened 2022-01-21 10:53 UTC by Devartjoker

# Description

- Add missing G$ logo on Stake page for Kovan network
- Fix floating point misplacement on Portfolio page by multiplying estimate $ values by 100
About # (link your issue here)
Resolves #107

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [x] PR title matches follow: (Feature|Bug|Chore) Task Name
- [x] My code follows the style guidelines of this project
- [x] I have followed all the instructions described in the initial task (check Definitions of Done)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [x] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2022-01-22 19:07 UTC, sirpy requested changes

2022-01-22 19:07 UTC, sirpy commented on src/components/PortfolioTableRow/index.tsx
> +                        .multiply(100)
this is a hack.
the fix should be fixing reward$.claimed and reward$.unclaimed, why are they not in the right precision?
check staking.ts

2022-01-22 19:07 UTC, sirpy commented on src/pages/gd/Portfolio/index.tsx
> +                                ~{data?.aggregated?.rewardsG$$.multiply(100).toFixed(2, { groupSeparator: ',' }) ?? '0.00'}$
fix in the source

2022-01-22 19:07 UTC, sirpy commented on src/pages/gd/Portfolio/index.tsx
> +                                ~{data?.aggregated?.rewardsG$Unclaimed$.multiply(100).toFixed(2, { groupSeparator: ',' }) ?? '0.00'}$
fix the source of the issue

2022-01-25 09:03 UTC, YpetrovAJ commented
@sirpy check the last commit here

2022-01-25 15:59 UTC, merged