feat: added claim screen
GoodDollar/GoodProtocolUI pull request #240
Opened 2022-09-27 17:02 UTC by alt-a1r

Added Claim screen and ClaimButton component. PR is draft because it should be checked after fixes regarding useGetContract hook

About #321

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2022-09-28 08:49 UTC, sirpy commented
@johnsmith-gooddollar all components should be in nativebase in the new goodweb3-mono ui package

2022-09-28 09:50 UTC, johnsmith-gooddollar commented
@alt-a1r ^^^^

2022-10-03 13:40 UTC, johnsmith-gooddollar requested changes

2022-10-03 13:40 UTC, johnsmith-gooddollar commented on src/components/SideBar.tsx
> +                      <div className="flex flex-col details">
Should be Box according nativebase docs: https://docs.nativebase.io/box

2022-10-03 13:40 UTC, johnsmith-gooddollar commented on src/pages/gd/Claim/ClaimButton/styled.ts
> +export const StyledButton = styled(ButtonPrimary)`
- all base/common styles for buttons etc should be defined by extendTheme https://docs.nativebase.io/customizing-components
- custom styles should be object (like in GD app) https://github.com/GeekyAnts/NativeBase/issues/4935#issuecomment-1144847331

2022-10-03 13:40 UTC, johnsmith-gooddollar commented on src/pages/gd/Claim/styled.ts
> +export const PageContent = styled.div`
migrate to nativebase (see comments above)

2022-10-03 13:40 UTC, johnsmith-gooddollar commented on src/pages/gd/Claim/index.tsx
> +		<StyledLayout classes="md:mt-24 xl:mt-0 sh:mt-30">
use NativeBase's layouts: read https://docs.nativebase.io/box and sections below

2022-10-04 06:42 UTC, sirpy commented
@alt-a1r @roma-hladilka @johnsmith-gooddollar 
most new components should be in the new good-design package

2022-10-04 09:26 UTC, alt-a1r commented
@sirpy Now buttons components (ClaimButton in particular) are imported from @good-design (I haven't updated PR yet because it's not merged in the @good-design)
Do we need to move any other components there? And which components need to be moved there at all (for future PR's)

2022-10-10 12:43 UTC, L03TJ3 commented on src/theme/nativeTheme.tsx
> +//TODO: move logic to good-design, no native-base logic here.
@alt-a1r consider this comment

2022-10-10 12:43 UTC, L03TJ3 commented on src/pages/gd/Claim/index.tsx
> +        <NativeBaseProvider theme={theme}>
@alt-a1r any styles should be defined either in the theme, or specifically styled on the component returned

2022-10-31 12:14 UTC, johnsmith-gooddollar requested changes

2022-10-31 12:14 UTC, johnsmith-gooddollar commented on src/pages/gd/Claim/index.tsx
> +    return (
```suggestion

    return (
```
pls add empty lines betweek code blocks, this increases readability

2022-10-31 12:14 UTC, johnsmith-gooddollar commented
pls add empty lines betweek code blocks, this increases readability

2022-11-10 13:54 UTC, closed without merging