draft: 253 ubeswap
GoodDollar/GoodProtocolUI pull request #257
Opened 2022-11-23 16:35 UTC by L03TJ3

# Description

Adding the ubeswap component when user is connected to celo

About # (link your issue here)
#253 

# How Has This Been Tested?
locally
Please describe the tests that you ran to verify your changes.

#todo
- [ ] Move component to good-design with a wrapper
- [ ] G$ logo is not loaded

2022-11-29 21:36 UTC, L03TJ3 commented
I think for now this basic implementation is enough there is not much configuration/styling that can be done

I suggest whenever the team open up their styling we move it to good-design

2022-11-30 17:39 UTC, johnsmith-gooddollar requested changes

2022-11-30 17:39 UTC, johnsmith-gooddollar commented on src/pages/gd/Swap/index.tsx
> +                                onClick: () => setBuying((value) => !value),
no inline callbacks, define them outside jsx as useCallback

2022-12-02 13:55 UTC, johnsmith-gooddollar approved these changes

2022-12-05 09:03 UTC, L03TJ3 commented
Current un-catched error on a user declining a connect wallet request. this originates from use-contract-kit
awaiting reply from ubeswap dev before merge

2022-12-15 19:26 UTC, johnsmith-gooddollar commented on src/pages/gd/Swap/SwapCelo/index.tsx
> +    return (
```suggestion

    return (
```

2022-12-15 19:27 UTC, johnsmith-gooddollar approved these changes

2022-12-21 08:24 UTC, merged