feature: Add more connect options
GoodDollar/GoodProtocolUI pull request #283
Opened 2023-01-02 14:30 UTC by L03TJ3

# Description

This will add:
- Social login with Torus
- Seperate wallet-connect button for GoodDollar wallet

About # (link your issue here)
#280 
#272 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2023-01-02 14:34 UTC, L03TJ3 commented
UI:
![image](https://user-images.githubusercontent.com/6606028/210245307-bee84bd6-46fb-43a3-a7ad-b6a677153839.png)

2023-01-04 15:57 UTC, L03TJ3 commented
The current status is that there is a general bug with onboard/torus when switching chains (also happens on their demo/default package)
I am on discord waiting for a response, it likely will become a GitHub issue on their repo

2023-01-04 16:33 UTC, johnsmith-gooddollar requested changes

2023-01-04 18:44 UTC, L03TJ3 commented on src/connectors/modules/Torus/torus.ts
> +function torus(options?: TorusOptions): WalletInit {
This is just done to be able to change the Label of the button, nothing more

2023-01-04 22:56 UTC, L03TJ3 commented on src/connectors/modules/CustomWc/EthProvider.ts
> +import WalletConnect from '@walletconnect/client'
PR created: https://github.com/GoodDollar/GoodWeb3-Mono/pull/39
draft implementation with last commit here

2023-01-31 17:59 UTC, johnsmith-gooddollar approved these changes

2023-01-31 23:14 UTC, L03TJ3 commented
@johnsmith-gooddollar the answer to that comment is that this is/was legacy code, and after looking at it I decided that it was not necessary to keep
update fetchListUpdate to use onboard library, tested, didn't see any problems arise from this change

2023-02-01 11:28 UTC, johnsmith-gooddollar approved these changes

2023-02-01 11:30 UTC, merged