add: new token balance view
GoodDollar/GoodProtocolUI pull request #518
Opened 2023-12-29 15:37 UTC by L03TJ3

# Description
this moves tokenbalance from side-bar to top-nav

- [ ] - add balance + icon to topnav for trigger the balance view
- [ ] - show token-balance in the window opened
- [ ] - add close when clicking on the bottom of the window 

About # (link your issue here)
#498 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

2024-01-02 17:00 UTC, johnsmith-gooddollar requested changes

2024-01-02 17:00 UTC, johnsmith-gooddollar commented on src/components/WalletBalance/index.tsx
> +        })
```suggestion
        const allTokens: any[] = [
        {
            type: 'ERC20',
            options: {
                address: G$.address,
                symbol: G$.ticker,
                decimals: G$.decimals,
                image: 'https://raw.githubusercontent.com/GoodDollar/GoodProtocolUI/master/src/assets/images/tokens/gd-logo.png',
            },
        }, {
            type: 'ERC20',
            options: {
                address: GOOD.address,
                symbol: GOOD.ticker,
                decimals: GOOD.decimals,
                image: 'https://raw.githubusercontent.com/GoodDollar/GoodProtocolUI/master/src/assets/images/tokens/good-logo.png',
            },
        }]
```

2024-01-08 03:00 UTC, L03TJ3 commented on src/components/AppBar.tsx
> +    const { G$ } = useG$Balance(5)
this is refresh rate, not chainId

2024-01-08 09:22 UTC, L03TJ3 commented on src/components/AppBar.tsx
> +    const [gdBalance, setGdBalance] = useState('0.00')
done

2024-01-08 09:22 UTC, L03TJ3 commented on src/components/WalletBalance/index.tsx
> +        })
done

2024-01-08 09:22 UTC, L03TJ3 commented on src/components/AppBar.tsx
> +
done

2024-01-08 15:45 UTC, johnsmith-gooddollar approved these changes

2024-01-08 17:19 UTC, merged